#+OPTIONS: f:nil author:nil num:1 creator:nil toc:1 timestamp:nil html-style:nil
** Copycat KFC
*** Ingredients
- 1 whole chicken (2 breasts, 2 thighs, 2 drumsticks, 2 wings)
- 2 quarts neutral oil, for frying
- 1 egg white
- 1 1/2 cups all-purpose flour
- 1 tablespoon brown sugar
- 1 tablespoon kosher salt
- 1 tablespoon paprika
- 2 teaspoons onion salt
- 1 teaspoon chili powder
- 1 teaspoon black pepper
- 1/2 teaspoon celery salt
- 1/2 teaspoon dried sage
- 1/2 teaspoon garlic powder
- 1/2 teaspoon ground allspice
- 1/2 teaspoon dried oregano
- 1/2 teaspoon dried basil
- 1/2 teaspoon dried marjoram
*** Method
1. Preheat fryer to 150°C. Thoroughly mix together all the spice mix
   ingredients.
2. Combine spice mix with flour, brown sugar and salt.
3. Dip chicken pieces in egg white to lightly coat them, then transfer
   to flour mixture. Turn a few times and make sure the flour mix is
   really stuck to the chicken. Repeat with all the chicken pieces.
4. Let chicken pieces rest for 5 minutes so crust has a chance to dry a
   bit.
5. Fry chicken in batches. Breasts and wings should take 15 minutes, and
   legs and thighs will need 20 minutes. Chicken pieces are done when a
   meat thermometer inserted into the thickest part reads 165°F.
6. Let chicken drain on a few paper towels when it comes out of the
   fryer. Serve hot.
*** Notes
**** 2018-03-08
- Tried doubling all spices (not flour)
- 2 egg whites
- *Didn't work*
**** <2018-04-29 Sun>
- cooked for 15 minutes for breast and 20 minutes for legs and thighs on
  150 degrees
** Salsa
*** Ingredients
- 6 ripe tomatoes
- 1 red pepper
- 1 big bunch of fresh coriander
- 1 onion
- 2 fresh jalapeño or green chillies
- 1 large clove of garlic
- 1 lime
- extra virgin olive oil
- 1tsp salt
*** Method
- Finely chop the tomatoes and coriander (stalks and all) and place into
  a large bowl.
- Peel and finely chop the onion, deseed and finely chop the chillies,
  then scrape into the bowl. Peel and finely grate in the garlic.
- Squeeze in the juice from 1 lime, add 2 tablespoons of extra virgin
  olive oil, and mix well. Season to taste with sea salt, black pepper
  and more lime juice, if needed.
- Serve straightaway or cover and set aside for a few hours to let all
  those flavours develop.
** Tacos
*** Ingredients
- 500g beef mince
- 1 onion, chopped
- 1 green pepper, chopped
- 1 garlic clove, crushed
- 2 teaspoon hot paprika
- 2 teaspoon ground cumin
- 1/2 teaspoon dried red chilli flakes
- 1/2 teasponn of cayenne pepper
- 6 tablespoons tomato puree
- 12 flour tortillas or taco shells
- peanut oil, for frying
- 1 tsp salt
- 1 tsp course ground peppper
*** Method
- Dry-fry the mince in a frying pan until brown and crumbly, stirring
  occasionally and breaking it up with a wooden spoon.
- Add the onion, green pepper and garlic; cook, stirring occasionally,
  until softened. Stir in the herbs and spices; season to taste with
  salt and pepper. Add the tomato puree and mix well. Cover and cook
  gently for 10 minutes, stirring occasionally.
- Place a little of the mixture on each tortilla and roll up, or spoon
  into the taco shells. Secure tortillas with a cocktail stick. If using
  tortillas, heat the oil in a frying pan and then fry the rolls quickly
  until golden. Serve with your choice of accompaniments.
** Fajitas
** Hot wings
*** Ingredients
- 3/4 cup all-purpose flour
- 1/2 teaspoon cayenne pepper
- 1/2 teaspoon garlic powder
- 1/2 teaspoon salt
- 20 chicken wings
- 1/2 cup melted butter (100g)
- 1/2 cup hot pepper sauce (such as Frank's RedHot®)
*** Method
- Line a baking sheet with aluminum foil, and lightly grease with
  cooking spray. Place the flour, cayenne pepper, garlic powder, and
  salt into a resealable plastic bag, and shake to mix. Add the chicken
  wings, seal, and toss until well coated with the flour mixture. Place
  the wings onto the prepared baking sheet, and place into the
  refrigerator. Refrigerate at least 1 hour.
- Preheat oven to 400 degrees F (200 degrees C).
- Whisk together the melted butter and hot sauce in a small bowl. Dip
  the wings into the butter mixture, and place back on the baking sheet.
  Bake in the preheated oven until the chicken is no longer pink
** Beef Pad Thai
*** Ingredients
- 1 cup dry roasted peanuts
- 1⁄3 cup water
- 1 garlic clove, minced
- 1⁄2 teaspoon dark soy sauce
- 2 teaspoons sesame oil
- 2 tablespoons brown sugar
- 1⁄4 teaspoon red pepper flakes (more or less to taste)
- 2 tablespoons asian fish sauce (If vegetarian, use vegetarian fish
  sauce or regular soy sauce)
- 1⁄2 teaspoon tahini paste
- 1 teaspoon red chili sauce (more or less to taste)
- 1 teaspoon lime juice
- lime zest
- 1 tablespoon peanut oil
- 1 teaspoon peeled and minced fresh ginger (you can find this in the
  oriental section of your grocery store) or 1 teaspoon sliced ginger in
  a jar (you can find this in the oriental section of your grocery
  store)
- 2 garlic cloves, minced
- 3 -4 tablespoons teriyaki sauce
- 1 cup cremini mushrooms, sliced or 1 cup shiitake mushroom
- 1 onion, sliced small onion, into long thin slices work best
- 1 lb lean beef steak, cut crosswise into 1/4 inch strips (such as
  sirloin tip or flank)
- 1⁄4 cup chopped dry roasted peanuts
- 1⁄4 cup chopped scallion (3-4 scallions, white & green parts)
- 8 ounces somen noodles or 8 ounces soba noodles, noodes or 8 ounces
  whole-wheat spaghetti
*** Instructions
**** Thai Peanut Sauce Preparation:
- Place the first 12 ingredients (from the peanuts to the lime zest), in
  a blender.
- Blend until sauce is smooth. If you prefer a runnier peanut sauce, add
  a little more water. Do a taste test for salt and spice, adding more
  fish sauce if not salty enough, and more chili sauce &/or red pepper
  flakes, if not spicy enough. If too salty, add another squeeze of
  fresh limejuice.
**** Beef Pad Thai Preparation:
- Cook the noodles according to the package directions. Drain, transfer
  to a large bowl, and cover with aluminum foil or plastic wrap to keep
  warm.
- Heat the peanut oil in a large skillet over medium-high heat. Add the
  ginger and garlic - cook, stirring, for 2 minutes. Add the sliced
  onions & mushrooms, stir-fry for 2 minutes. Add the beef and stir-fry
  another 2 minutes. Next, add the teriyaki sauce & a 1/2 cup of the
  Thai peanut sauce, stir all together, and simmer until the beef is
  cooked through, about 4-5 minutes.
- Transfer the noodles to the beef mixture & toss to combine. Serve on
  individual plates topped with the peanuts and scallions. The leftover
  peanut sauce will keep in the refrigerator up to 4 days or in the
  freezer up to 3 months; thaw completely in the refrigerator or
  microwave for about 3 minutes on LOW before using.
** Silverside Roast Beef
*** Ingredints
- Silver side beef joint
- 1 tbsp beef dripping or butter
- 1 tsp salt and some freshly ground black pepper
- 8-12 small red onions, peeled and slit in a cross at the pointed end
  (so that they do not burst in the oven)
- 4 heads garlic, halved horizontally
- A few sprigs of thyme
- Buttered spinach to serve.
- Celery stick
*** Method
- Preheat the oven to 210°C. Rub the rolled silverside joint with the
  beef dripping and sprinkle with plenty of salt and pepper.
- Add onions and garlic, thyme and celery - chopped but not peeled to
  the base of the tin as a trivet. Place beef on top.
- Place into the hot oven for 25 minutes to brown. Then reduce the oven
  temperature to 180°C.
- Add 100 ml of water.
- Cover with foil and cook , basting from time to time and adding a
  little more water if necessary. This will keep the meat moist.
  Re-cover with the foil each time.
- Cook for 25 mins per 450g in total
- Uncover the meat for the last 15 minutes of cooking.
- Remove the meat to a warm serving dish with the onions and garlic,
  cover well and keep it warm.
- Slice the beef and serve a couple of slices per person with the soft
  onions, a piece of garlic, the Yorkshire puddings and a spoon or two
  of gravy and your favourite green leafy vegetable, such as spinach.
*** Notes
<2018-04-29 Sun>
- 15:55 Beef in
- 16:20 beef turned down
- 17:00 Start cooking potatoes
- 17:40 Potatoes in oven
- 17:45 Uncover meat and turn up oven to 210
- 18:00 peas and carrots
- 18:00 flip potatoes
- 18:00 beef out to rest
- 18:00 Start Yorkshire puddings
- 18:20 Yorkshire puddings out
- *Yorkshires were shit - find another recepie*
** Crispy Pork Belly
*** Ingredients
- 1/2 pound whole pork belly, skin removed
- 1/2 teaspoon smoked paprika, or to taste
- kosher salt and ground black pepper to taste
- 1 tablespoon olive oil, or to taste
*** Method
- Preheat oven to 200 degrees F (95 degrees C).
- Season pork belly all over with smoked paprika, salt, and black
  pepper. Wrap pork in parchment paper; wrap a second time in aluminum
  foil, and a third time in another sheet of aluminum foil. Place pork
  packet in a baking dish.
- Roast in the preheated oven until tender for 6 hours. Let cool in
  wrappings to room temperature; place cooled packet in refrigerator and
  chill for 8 hours or overnight.
- Unwrap chilled meat. Save any rendered fat that falls away when
  unwrapping pork.
- Cut meat into 6 equal-size portions. Cut 1/8-inch by 1/8-inch slashes
  in the fat-side of the pork. Season with salt.
- Heat 2 tablespoons reserved pork fat in a skillet over medium heat.
  Place pork belly, fat side down, in hot fat; cook until well-browned
  on all sides and heated through, 5 to 10 minutes. Transfer pork belly
  to a plate, drizzle with olive oil and season with pepper.
** Yorkshire Puddings
*** Ingredients
- 4oz Flour
- 8oz Milk
- 2 eggs
- pinch salt
- Tbsp Oil
*** Method
- Oven temperature to 210°C.
- In a large bowl mix the flour and salt, make a well in the centre,
  break in the eggs and hand whisk in half the liquid, gradually
  incorporating the flour as you whisk until you have a smooth thick
  batter with no lumps.
- Stir in the remaining liquid and leave to stand.
- Put 1/2 a teaspoon of beef dripping into each of the muffin cups.
- Place the muffin tin in the oven until the fat is very hot, stir the
  batter well, then 2/3 fill each muffin cup and return to the oven for
  about 20 minutes until well risen and golden brown. They should feel
  firm and in no danger of collapse, so leave them in a little longer if
  necessary.
** Roast Poatoes
*** Ingredients
- Potatoes
- 2 tbsp plain flour
- 3 tbsp sunflower oil
*** Method
- An hour before roast is ready, start the potatoes
- Peel and halve potatoes and bring to boil in a pan of cold water. Boil
  for 2 minutes exactly.
- Drain potatoes and toss in colinder, adding flour.
- Add oil to a roasting tin over high heat, when sizzling add potatoes
  and cook for 5 minutes, ensuring even coating of oil
- Roast undistrubed for 20 min, then turn and roast for another 20
  minutes.
*** Notes
  - Used Gooes fat - and worked amazingly well
** Gravy
*** Ingredients
- 100 ml red/white wine
- 100 ml water
- 1 tbsp Dijon or English mustard
*** Method
- Discard any fat from the surface of the pan juices, and with the pan
  over a medium heat stir in the wine and gather up all the sticky bits,
  add the water and the port or redcurrant jelly and when melted simmer
  to reduce the liquid a little.
- Add the mustard and stir until thickened. Taste and season as
  necessary.
** Sauteed Kale
*** Ingredients
- 1 pound kale leaves (dark green, stem removed and leaves chopped, then
  washed and dried)
- 1 tablespoon extra-virgin olive oil (or slightly more, depending on
  your pan)
- 1 red onion (chopped in small pieces, or use about 1/2 cup chopped
  shallots)
- 2 cloves garlic (fresh, very finely minced)
- 2 cups water (added 1/2 cup at a time)
- 1 tbsp white wine vinegar
*** Method
- Chop the onion or shallots and finely mince the garlic, then heat oil
  in heavy frying pan until it's medium-hot and saute onion 3-4 minutes
  until it starts to brown. When onion is turning slightly brown, add
  garlic and saute 1 minute more.
- While onions and garlic cook, cut away the center rib from each kale
  leaf and discard. Chop or tear the kale leaves into bite-sized pieces,
  then wash and spin dry or dry with paper towels.
- Add chopped kale leaves to the browned onion/garlic mixture, season
  generously with salt and fresh ground black pepper, and let the kale
  wilt for 2-3 minutes, then add 1/2 cup water, stir, and let the kale
  cook in the water until the pan is almost dry, about 5-10 minutes.
- Add 1/2 cup more water and cook kale 5-10 minutes more, then add a
  third 1/2 cup of water and cook kale 5-10 minutes more. After you've
  added water and cooked it off three times, taste to see if the kale is
  tender; if not, add water one more time and cook a bit longer.
- When kale is melt-in-your-mouth tender and the pan is nearly dry,
  season as desired with vinegar and serve hot or warm.
** French Fries
*** Ingredients
- 8 cups cold water
- 2 tablespoons fine sea salt
- 2 1⁄2 teaspoons granulated sugar
- 1 teaspoon white pepper
- 2 tablespoons white vinegar
*** Method
- PEEL 4 medium russet potatoes; CUT potatoes into 1/4" shoestrings (try
  to make them as uniform as possible; I use an adjustable-blade
  French-fry cutter).
- PLACE cut potatoes into the brine container; SEAL and refrigerate for
  at least 2 hours; BRING pot with brine and potatoes to a full boil;
  BOIL for 1 1/2-2 minutes; DRAIN and rinse potatoes under cold water;
  BLOT potatoes as dry as possible.
- PLACE potatoes side-by-side into freezer bags without touching, and
  without crowding; SEAL bags and freeze flat in refrigerator for at
  least 2 hours (just make sure fries are frozen solid).
- FILL deep-fryer with proper amount of beef tallow (or oil/shortening
  blend), to manufacturer's recommended amount; HEAT fryer in gradual
  increments to 375°F.
- PLACE 1/2 of the potatoes at a time into elevated deep-frying basket;
  GENTLY lower basket into hot fat.
- FRY for about 2 minutes but PAY ATTENTION TO THE COLOR -- potato color
  should be light golden brown with just slightly darker ends (see
  photo, and pull a french fry with tongs to test doneness if
  necessary); ELEVATE fry basket and shake to drain excess fat; SECURE
  basket and let drain for 30 seconds.
- TRANSFER fries into colander placed in sink; REPEAT with remaining
  potatoes.
** Burgers
*** Ingredients
- 1 egg
- 1 teaspoon mustard (regular or Dijon)
- 1 teaspoon Worcestershire sauce
- 1 small onion, finely grated
- 1 clove garlic, minced
- 1⁄2 teaspoon salt
- 1⁄2 teaspoon pepper
- 500g medium ground beef
**** Stirins
- 1 teaspoon dried mixed herbs
- 2 teaspoons cajun seasoning
- 1 tbsp fresh herbs
*** Method
- Lightly oil grill
- Whisk egg in a bowl& add next 6 ingredients.
- Add any of the “stir-ins” that appeal to you.
- Crumble in beef using your hands or a fork, gently mix together.
- Handle the meat as little as possible -- the more you work it, the
  tougher it gets.
- Gently shape (don't firmly press) mixture into burgers about ¾ inch
  thick.
- Heat up lightly oiled grill and when hot turn to medium heat (about 4
  minutes)
- Place burgers on the grill and cook 4 minutes on each side
- Tuck into a warm crusty bun add your favourite toppings.
** Peri Peri Chicken
*** Ingredients
- 4 chicken breasts (I used skinless and boneless)
- Salt and pepper to taste
- 2 tablespoons olive oil
- 2 cups peppers, chopped (I used red, yellow and orange)
- 4--6 thin slices of lemon
- 2 sprig fresh thyme
- 2 sprigs fresh rosemary
**** Peri Peri Marinade:
- 3 cloves garlic, peeled and roughly chopped
- 1/2 teaspoon crushed red pepper flakes
- 1 tablespoon smoked paprika
- 1/4 cup lime juice / 1 Large Lime
- 1/4 cup olive oil
- 1 tablespoon red wine vinegar
*** Method
- To make the peri-peri marinade: place all the ingredients in the bowl
  of a small food processor and process until puréed.
- Season chicken with salt and pepper to taste. Place the chicken in a
  large sealable plastic bag. Add the peri-peri marinade and close. Rub
  the bag to coat the chicken in the marinade then refrigerate for 4
  hours, or overnight.
- Preheat the oven to 200°C
- Remove the chicken from the bag and drain off the excess marinade.
  Reserve marinade.
- Heat oil in a skillet over medium-high heat. Place chicken in the
  skillet and brown each side until nice golden color. Turn off heat.
  Add reserved marinade, peppers, lemon slices, thyme, and rosemary,
  over the chicken. Cover the skillet with parchment paper.
- Bake for 20 - 30 minutes, or until the chicken reaches an internal
  temperature of 165º F in the thickness part. Cooking time will depend
  on the size of the chicken breasts. Remove from oven and allow to
  rest, covered, for 10 minutes.
- Serve with the lime wedges and pan juices.
** Garlic Rice
*** Ingredients
- 40g Salted Butter
- 9 to 12 Cloves garlic (approximately 2 heaping Tbs)
- 2 cups Jasmine rice
- 3 cups Water
- 1 Green onion
- Cilantro
*** Method
- Heat a large thick bottom pot that has lid over low heat. Add butter
  and let it slowly melt.
- Meanwhile roughly chop garlic and onion. Add into melted butter and
  increase heat to medium. Fry garlic for 4 to 5 minutes until garlic is
  golden brown and crispy. Stir occasionally so they will cook evenly.
  Be careful not to burn, it will give bitter flavor.
- Turn off heat and take fried garlic out on a plate with paper towel.
  Set aside.
- Turn back heat to medium; add rice into beautiful garlic infused
  butter. Stir to coat every single grain of rice with butter and toast
  them for 1 to 2 minutes until rice absorbed butter and toasted evenly.
  Stir occasionally.
- Add water; stir once and cover with lid. Increase heat to high and
  bring it to boil. When it starts boiling, reduce heat to low and stir
  one last time from bottom to top with an wooden spoon. Cover back on,
  simmer for 10 minutes.
- Remove from heat and let it sit for 10 extra minutes so rice will
  finish cooking. Don't open lid in this process, because rice will need
  all hot steam inside of pot to finish cooking.
- Meanwhile, chop green onion and some cilantro for garnish.
- Now, finally open and fluff rice from bottom to top with a spoon or
  fork. Garnish with chopped green onion, cilantro and fried garlic.
  Serve hot and let your guest to mix the rice and garnish. Enjoy!
** BBQ Brisket
*** Ingredients
- 1.5 -- 2 kg / 3 -- 4 lb beef brisket (Note 1)
- 500 ml/ 18 fl oz beef stock
**** Rub:
- 1 tbsp brown sugar
- 2 tsp paprika powder
- 1 tsp onion powder
- 1 tsp garlic powder
- 1/2 tsp cumin powder
- 3/4 tsp mustard powder
- 1 tsp salt
- 1/2 tsp black pepper

**** BBQ Sauce:
- 1 tbsp sunflower oil
- 1 small onion, finely chopped
- 3 garlic cloves, crushed
- 500 ml/ 18 fl oz tomato ketchup
- 100 ml/ 3½ fl oz Worcestershire sauce
- 75 ml/ 2½ fl oz lemon juice
- 2 tbsp brown sugar
- 1 tbsp malt vinegar
- 2 tsp Dijon mustard
- 1 tsp crushed chilli flakes
- 1 tsp Tabasco sauce
- 1 tsp dried thyme
*** Method
- To make the barbecue sauce, heat the oil in a frying pan, then cook
  onion and garlic for a few mins until soft. Add the rest of the sauce
  ingredients to the pan with a good pinch of salt and simmer for 20
  mins. Use a hand blender or food processor to whizz to a smooth purée.
- Heat oven to 150C/130C fan/gas 2. Make the rub by mixing all the
  ingredients together with a pinch of salt. Rub the mix all over the
  beef and set aside.
- In a large roasting tin, mix the beef stock and ½ the barbecue sauce.
  Add the brisket to the tin, cover tightly with foil, then cook for 4-5
  hrs until the meat is really tender when you push a fork into it. The
  beef can be prepared the night before -- just leave it to cool in the
  tin covered with foil, but don't refrigerate.
- To finish the beef, get a barbecue fired up and wait until the coals
  are completely ashen -- you want a low, not fierce, heat. Lift the
  beef out of the roasting tin and place on the barbecue to char. If
  your barbecue has a lid, close it now. Cook for about 20 mins, turning
  it carefully with tongs, until lightly charred all over and heated
  through. Lift onto a board and serve sliced with the remaining
  barbecue sauce on the side.
** Pork ribs
*** Ingredients
- 1/4 cup salt
- 1/4 cup white sugar
- 2 tablespoons brown sugar (packed)
- 2 tablespoons ground black pepper
- 2 tablespoons ground white pepper
- 2 tablespoons onion powder
- 1 tablespoon garlic powder
- 1 tablespoon chili powder
- 1 tablespoon paprika
- 1 tablespoon ground cumin
- 10 pounds pork baby back ribs
- 1 cup apple juice
- 1/4 cup brown sugar (packed)
- 1/4 cup barbecue sauce
*** Method
- Stir salt, white sugar, 2 tablespoons brown sugar, black pepper, white
  pepper, onion powder, garlic powder, chili powder, paprika, and cumin
  together in a small bowl to make the dry rub. Rub the spice mixture
  into the baby back ribs on all sides. Wrap the ribs well with plastic
  wrap, and refrigerate for at least 30 minutes prior to cooking.
- Unwrap baby back ribs and place onto the wire racks of the smoker in a
  single layer.
- Place the racks into a smoker, fill the smoker pan with apple, grape,
  pear, or cherry chips, and bring the smoker to 270 degrees F (130
  degrees C). Smoke for 1 hour.
- Stir together the apple juice, 1/4 cup brown sugar, and the barbeque
  sauce. Brush the ribs with the sauce every 30 to 45 minutes after the
  first hour. Cook the ribs in the smoker until the meat is no longer
  pink and begins to "shrink" back from the bones, 3 to 4 hours. Brush
  the sauce onto the ribs one last time 30 minutes before the ribs are
  ready to be taken out of the smoker.
- Once the ribs are done, wrap them tightly with aluminum foil, and
  allow to rest 10 to 15 minutes. This will allow the juices to reabsorb
  into the meat and make the ribs moist.
** Beef and Ale Pie
*** Ingredients
**** Meat
- small handful dried porcini mushrooms (about 10g) - not essential but
  very tasty
- 2 tbsp vegetable oil
- 1kg braising steak (buy this as a whole piece and cut it yourself into
  large chunks)
- 2 large onions
- Onion roughly chopped
- 4 large carrots chopped into large chunks
- 2 tsp golden caster sugar
- 4 tbsp plain flour
- 300ml dark ale
- 2 beef stock cubes mixed with 400ml boiling water
- small bunch each thyme bay leaf and parsley, tied together
- 200g smoked bacon lardons, or chopped rashers
- 200g chestnut mushroom, halved
**** For the pastry
- 650g plain flour, plus extra for dusting
- 250g lard or cold butter (or half of each), diced, plus extra for
  greasing
- 1 egg yolk, beaten, to glaze

*** Method
- Start by braising the beef. If you're using the porcini, cover them in
  boiling water for 20 mins, then squeeze out but keep the soaking
  water. Heat oven to 160C/140C fan/gas 3. Heat half the oil in a large
  casserole dish, brown the meat really well in batches, then set aside.
- Add the onions and carrots to the pan, adding a drizzle more oil, then
  cook on a low heat for 5 mins until coloured. Add the soaked
  mushrooms, sizzle for 1 min more, then scatter over the sugar and
  flour, stirring until the flour turns brown. Tip the meat and any
  juices back into the pan and give it all a good stir. Pour over the
  ale, stock and porcini soaking liquid, discarding the last few drops.
  Season stew, tuck in the herbs and bring everything to a simmer. Cover
  with a lid and place in the oven for about 2 hrs, until the meat is
  really tender.
- While the stew is cooking, heat a drop more oil in a frying pan and
  sizzle the bacon for 3 mins until crisp. Turn up the heat, add the
  mushrooms and cook for 4 mins until golden. Remove from the heat and,
  when the stew is cooked, stir them through.
- Leave everything to cool completely -- better still, make this up to 2
  days in advance and keep it in the fridge as the pie will be better if
  the filling is fridge-cold when added. Can also be frozen for up to 3
  months and defrosted when needed.
- Make the pastry up to 2 days before you want to assemble the pie.
  Crumble the flour and lard, or butter, together with a generous pinch
  of sea salt until completely combined, then add up to 200ml ice-cold
  water to make a soft dough. This can be done in a food processor if
  you want.
- Knead the pastry, then wrap in cling film and leave to rest in the
  fridge for at least 1 hr. The pastry can be made up to 2 days ahead
  and kept in the fridge or frozen for up to a month.
- When you want to make the pie, heat oven to 220C/200C fan/gas 7 and
  place a flat baking tray in the oven. Heavily grease a 24-28cm pie
  dish and dust well with flour. Cut a third off the pastry and set
  aside. Roll out the pastry to a thick-ish round that will easily line
  the pie dish with an overhang, then line the tin.
- Add the beef to the dish using a slotted spoon so some gravy is left
  in the container, as you don't want too much sauce in the pie. You
  want the filling to be slightly higher than the rim of the dish. If
  you have a bit too much, set it aside.
- Roll out the remaining pastry to a thick round big enough to cover the
  dish. Brush the edges of the pastry in the dish with egg yolk, then
  cover with the pastry lid. Trim the edges, crimp the pastry, then
  re-roll your trimmings to make a decoration, if you like -- I always
  decorate my pies with pastry leaves. Brush the top heavily with egg.
  Make a few little slits in the centre of the pie, place on the hot
  baking tray.
- Bake for 40 mins until golden. Leave the pie to rest for 10 mins while
  you heat up the gravy left in the container. Serve the pie at the
  table with a jug of gravy and a big pile of something green and leafy.

** Meatloaf
*** Ingredients
**** Meatloaf Ingredients:
- 2 lbs ground beef 85% or 90% lean
- 1 med onion finely chopped
- 2 large eggs
- 3 garlic cloves minced
- 3 Tbsp ketchup
- 3 Tbsp fresh parsley finely chopped
- 3/4 cup Panko breadcrumbs
- 1/3 cup milk
- 1 ½ tsp salt or to taste
- 1 ½ tsp Italian seasoning
- ¼ tsp ground black pepper
- ½ tsp ground paprika
**** Meatloaf Sauce Ingredients:
- 3/4 cup ketchup
- 1 ½ tsp white vinegar
- 2 ½ Tbsp brown sugar
- 1 tsp garlic powder
- ½ tsp onion powder
- ¼ tsp ground black pepper
- ¼ tsp salt
*** Method
1. Line a 9”x5” loaf pan with parchment paper and preheat oven to 375°F.
1. In a large bowl, add all of the ingredients for the meatloaf. Mix well to 1. combine.
Add meat to the loaf pan, gently press meat down and shape evenly and bake 1. meatloaf at 375˚F for 40 minutes.
1. In a small bowl, mix all of the ingredients together for the sauce. Spread the sauce over meatloaf then return to oven and bake additional 15-20 minutes. 1. Rest meatloaf 10 minutes before slicing. Drizzle with baking juices from the pan.
** Gumbo
*** Ingredients
- 1 x Pack of fresh cut coriander (Leave a little to the side for garnish)
- 1 x Pack of fresh cut flat leaf parsley
- 4 x Cloves of garlic (more if you wish)
- 1 x Root of fresh ginger
- 1 x Fresh lemon grass stalk
- 2 x White cooking onions
- 1 x Vegetable stock cube
- 500ml of water
- 250ml (1/2 a Carton) of Passata
- 1 x Chilli pepper (De-seeded)
- Half a pack of celery
- 2 x Bell peppers (I use yellow and red for colour and flavour)
- Plus any additional Vegetables of your choice
- 2 x Pack of Aldi frozen raw king prawns £2.29
- 1 x Pack of The Fishmonger Scottish Mussels in White Wine Sauce
*** Method
1. In a blender put the 4 x garlic cloves, chilli pepper, half of the coriander, the parsley, onions and half the pealed ginger to finely chop. Simply add to a large pan with a little virgin oil and cook off. If using raw chicken pieces to replace the prawns add them at this stage.
1. Add half the water, vegetable stock cube and lemon grass stalk (bash and split the stalk to open it up so the flavours can get out). Simmer to let the flavours from the spices come through for about 10 minutes.
1. Add the remaining vegetables and let cook for a further 10 minutes, add salt to taste and more chilli if you want the dish to be hotter. then add and stir in the passata (250ml half a carton) and put to one side.
1. In a large pan that has a lid add a knob of butter, garlic, coriander and king prawns, once they turn pink generally 5 – 6 minutes they are cooked and put to one side in a dish, try not to over cook the prawns as they will go chewy.
1. Add the mussels and all of the white wine sauce contents from the pack, follow the instructions on the back of the pack for cooking times. Once the mussels are cooked add the king prawns back to the pot and then ladle in the Gumbo broth and vegetables, bring the broth back to simmering.
1. If you have guests over I typically wait to do the king prawns and mussels just before we are ready to eat so they’re cooked fresh and hot. Garnish with coriander and pop the pot on the table with the ladle, this is a great rustic sharing dish to serve with crusty bread.
** Oxtail Stew
*** Ingredients
- 2.5 kg oxtail , chopped into 4cm chunks (ask your butcher to do this)
- olive oil
- 2 medium leeks
- 2 sticks of celery
- 4 medium carrots
- a few sprigs of fresh thyme
- a few sprigs of fresh rosemary
- 4 fresh bay leaves
- 4 cloves
- 2 heaped tablespoons plain flour
- 2 x 400 g tins of plum tomatoes
- 275 ml porter or red wine
- 1 litre organic beef stock , optional
- Worcestershire sauce
*** Method
1. Preheat the oven to 220ºC/425ºF/gas 7. Place a large roasting tray in the oven to preheat.
2. Carefully remove the hot tray from the oven, then add the oxtail. Season and drizzle over a lug of olive oil, then toss to coat and place in the hot oven for around 20 minutes, or until golden and caramelized.
3. Meanwhile, trim and halve the leeks and celery lengthways, then chop into rough 2cm chunks. Peel and chop the carrots into 2cm pieces, then place into a large ovenproof casserole pan over a medium-low heat with 1 tablespoon of olive oil.
4. Pick, roughly chop and add the thyme and rosemary leaves, then add the bay and cook for around 20 minutes, or until soft and sweet, stirring frequently.
5. Meanwhile, remove the oxtail from the oven and set aside. Reduce the oven temperature to 170ºC/325ºF/gas 3.
6. Add the cloves and flour to the veg, stirring well to combine, then pour in the tomatoes and porter (or wine, if using). Add the oxtail and any roasting juices, cover with the beef stock or 1 litre of cold water and stir well.
7. Turn the heat up to high and bring to the boil, then pop the lid on and place in the hot oven for around 5 hours, or until the meat falls away from the bone, stirring every hour or so and adding a splash of water to loosen, if needed.
8. Remove the pan from the oven and leave to cool for about 10 minutes. Using rubber gloves, strip the meat from the bones and return to the pan, discarding the bones.
9. Add a good splash of Worcestershire sauce, season to taste and enjoy with creamy mash and seasonal steamed greens.
   
** Pork belly slow roast
*** Ingredients
- 2 pounds pork belly with skin
- 1 to 2 tablespoons extra virgin olive oil
- Dash Kosher salt
- Dash freshly ground black pepper
*** Method
1. Heat the oven to 180 C
1. With a sharp knife, make several parallel cuts across the skin of the pork belly. Cut through the skin and fat but not into the meat. Place the cuts about 1/4-inch apart.
1. Rub the pork all over with kosher salt and freshly ground black pepper. Drizzle with olive oil and rub that in.
1. Place the pork on a rack in a baking pan, skin side up. 
1. Roast for 2 to 2 1/2 hours, or until the meat is very tender and falling apart. Increase the heat to 220 C and roast for about 20 minutes longer to crisp the skin more.
1. Remove and let rest for 10 minutes before slicing.
** Baked Portobello Mushrooms
*** Ingredients
- 2 large portabello mushrooms
- 2 Tbsp. soy sauce use tamari if needed to be gluten free
- 1 Tbsp. balsamic vinegar
- 0.5 tsp. minced garlic
- 0.25 tsp. minced or grated ginger root
- 0.5 Tbsp. olive oil
*** Method
1. Preheat oven to 205°C.
1. Find a baking dish that will fit both mushroom caps (tightly line dish in foil to make clean up easier if desired). Add all ingredients except mushroom caps and stir to create marinade.
1. Add mushrooms and rub sauce onto them. Let sit for 15 minutes, stem side down.
1. Once 15 minutes is up, rub mushrooms again with sauce before placing dish in the oven.
1. Bake for 15 minutes. Remove and turn mushrooms over. If there is any sauce left in the pan, spoon it over the mushrooms. Continue baking another 5-15 minutes (exact cooking time will vary based on mushroom size).
1. Remove mushrooms and let sit for 5 minutes before slicing and serving.
** Spaghetti Bolognese 
*** Ingredients
- 1 tbsp olive oil
- 4 rashers smoked streaky bacon, finely chopped
- 2 medium onions, finely chopped
- 2 carrots, trimmed and finely chopped
- 2 celery sticks, finely chopped
- 2 garlic cloves, finely chopped
- 2-3 sprigs rosemary
- Rosemary, leaves picked and finely chopped
- 500g beef mince
- 2 x 400g tins chopped tomatoes
- small pack basil, leaves picked, ¾ finely chopped and the rest left whole for garnish
- 1 tsp dried oregano
- 2 fresh bay leaves
- 2 tbsp tomato purée
- 1 beef stock pot
- A dash of Worcestershire sauce
- 1 red chilli, deseeded and finely chopped (optional)
- 125ml red wine
- 6 cherry tomatoes, sliced in half
- 400g spaghetti
*** Method
1. Put a large saucepan on a medium heat and add 1 tbsp olive oil.
2. Add 4 finely chopped bacon rashers and fry for 10 mins until golden and crisp.
3. Reduce the heat and add the 2 onions, 2 carrots, 2 celery sticks, 2 garlic cloves and the leaves from 2-3 sprigs rosemary, all finely chopped, then fry for 10 mins. Stir the veg often until it softens.
4. Increase the heat to medium-high, add 500g beef mince and cook stirring for 3-4 mins until the meat is browned all over.
5. Add 2 tins plum tomatoes, the finely chopped leaves from ¾ small pack basil, 1 tsp dried oregano, 2 bay leaves, 2 tbsp tomato purée, 1 beef stock pot, 1 deseeded and finely chopped red chilli (if using), 125ml red wine and 6 halved cherry tomatoes, and the Worcestershire sause.
6. Stir with a wooden spoon
7. Bring to the boil, reduce to a gentle simmer and cover with a lid. Cook for 1 hr 15 mins stirring occasionally, until you have a rich, thick sauce.
8. When the bolognese is nearly finished, cook 400g spaghetti following the pack instructions.
9. Drain the spaghetti and stir into the bolognese sauce.
** Peppered mackeral fishcakes
*** Ingredients
- 300g cold mashed potato
- 6 spring onions, thinly sliced
- 1 tbsp horseradish sauce
- 250g / 9oz peppered mackerel fillets, skinned and flaked
- 2 tbsp plain flour
- 1 egg, beaten
- 85g dried breadcrumbs
*** Method
1. In a large bowl, mix together the potato, spring onions, horseradish and mackerel, then shape into 8 even-size cakes. Roll the fishcakes in the flour, shaking off any excess, then dip in the egg, followed by the breadcrumbs. Cover and chill until ready to cook. Can be prepared up to a day ahead, or frozen.
1. Gently grill or shallow-fry the fishcakes for 5-6 mins on each side until crunchy, golden brown and hot all the way through. Serve with salad and lemon wedges.
** Sausage and bean casserole
*** Ingredients
- 2 tbsp olive or rapeseed oil
- 1 onion, finely chopped
- 2 medium sticks celery, finely chopped
- 1 yellow pepper, chopped
- 1 red pepper, chopped
- 6 cooking chorizo sausages (about 400g)
- 6 pork sausages (about 400g)
- 3 fat garlic cloves, chopped
- 1½ tsp sweet smoked paprika
- ½ tsp ground cumin
- 1 tbsp dried thyme
- 125ml white wine
- 2 x 400g cans cherry tomatoes or chopped tomatoes
- 2 sprigs fresh thyme
- 1 chicken stock cube
- 1 x 400g can aduki beans, drained and rinsed
- 1 bunch chives, snipped (optional)
*** Method
1. Heat 2 tbsp olive or rapeseed oil in a large heavy-based pan.
1. Add 1 finely chopped onion and cook gently for 5 minutes.
1. Add 2 finely chopped medium celery sticks, 1 chopped yellow pepper and 1 chopped red pepper and cook for a further 5 mins.
1. Add 6 chorizo sausages and 6 pork sausages and fry for 5 minutes.
1. Stir in 3 chopped garlic cloves, 1 ½ tsp sweet smoked paprika, ½ tsp ground  cumin and 1 tbsp dried thyme and continue cooking for 1 – 2 mins or until the aromas are released.
1. Pour in 125ml white wine and use a wooden spoon to remove any residue stuck to the pan.
1. Add two 400g cans of tomatoes, and 2 sprigs of fresh thyme and bring to a simmer. Crumble in the chicken stock cube and stir.
1. Cook for 40 minutes. Stir in a 400g drained and rinsed can of aduki beans and cook for a further five minutes.
1. Remove the thyme sprigs, season with black pepper and stir through some snipped chives, if using. Serve.
** Braised Leeks
*** Ingredients
- 6-8 leeks
- 1 tsp olive oil
- 2 tsp coriander seeds
- 3 thyme sprigs
- 2 bay leaves
- 125ml white wine
- 1 garlic clove with the skin on, bashed
- pinch caster sugar
*** Method
1. Trim the darkest green part off the leeks and strip away the first two layers. Cut in half lengthways, but keep attached at the root. Wash the leeks under cold running water and set aside.
1. Tip all the other ingredients into a wide shallow pan with 200ml water, some cracked pepper and a sprinkling of salt.
1. Slip the leeks into the pan, cover and place over a low heat. Gently simmer for 20 mins, turning them occasionally until very tender – a knife blade should slip in easily.
1. Leave to cool until just warm, then stir through the parsley and olives, if you like. Serve the leeks as they are with crusty bread or with roast chicken or fish
** Fried Green Beans
*** Ingredients
- 2 tbsp sunflower oil
- 200g pack trimmed green beans
- 3 garlic cloves, finely sliced
*** Method
1. Heat the oil in a wok, then stir-fry the green beans for 5 mins until they start to brown. Add the garlic and continue to cook until just tinged brown, then splash in the oyster sauce and serve.
** Tuna Steaks (Mediterranean)
*** Ingredients
- 6 tbsp good-quality olive oil
- 1 large yellow onion chopped
- 3 cloves garlic 2 minced and 1 crushed
- 1 cup Roma tomatoes I love San Marzano, drained and chopped
- 8 fresh basil leaves roughly chopped
- 2 tbsp fresh flat-leaf parsley chopped, plus more for garnish
- 4 tuna steaks each about 1/2 lb
- Kosher or Sea salt and freshly ground pepper
- 1 cup pitted black olives left whole, or, sliced/chopped
- 4 tsp capers rinsed
*** Method
1. In a large skillet over medium heat, warm 3 tablespoons of the olive oil.
2. Add the onion and saute until it begins to soften, about 3 minutes.
3. Add the minced garlic and saute until golden, about 2 minutes longer.
4. Stir in the tomatoes, basil and 2 tablespoons of the parsley and cook, uncovered, stirring occasionally, until slightly thickened, about 15 minutes.
5. Remove from heat and set aside.
6. Lightly season the tuna steaks on both sides with salt and pepper.
7. In another skillet, large enough to hold the fish in a single layer, warm the remaining 3 tablespoons olive oil over medium heat.
8. Add the crushed garlic and cook, stirring often, until golden, about 2 minutes. Remove and discard the garlic.
9. Add the tuna steaks to the skillet, raise the heat to medium-high, and cook, turning once, until lightly browned on both sides, about 2 - 3 minutes per side.
10. Pour the reserved sauce directly over the fish, reduce the heat to low, and add the olives and capers, and cook for another 5 minutes (sauce will thicken a little more).
11. Transfer tuna steaks and sauce to plates and garnish with parsley.
** BBQ Pork Ribs
*** Ingredients
**** BARBECUE RUB FOR RIBS:
- 2.5 tsp paprika powder
- 2 tsp garlic powder (sub with onion powder)
- 1.5 tsp onion powder (sub with garlic powder)
- 1 tsp cayenne pepper (omit for not spicy)
- 1.5 tsp dried thyme
- 1.5 tsp dried oregano
- 1.5 tsp salt
- 0.5 tsp black pepper
**** RIBS
- 2 - 2.5kg / 4 - 5lb pork ribs (2 racks)
- 3/4 cup (185ml) sweet alcoholic apple cider
- 1 tbsp olive oil
**** HOMEMADE BARBECUE SAUCE
- 1/2 cup (125ml) apple cider vinegar (Note 3)
- 1 1/2 cups tomato ketchup (or Aussie tomato sauce)
- 1/2 cup (125ml) water (or use remaining apple cider!)
- 1.5 tbsp molasses , orginal (not blackstrap, Note 4)
- 1/3 cup brown sugar
- 2 tsp mustard powder
- 1.5 tsp garlic powder
- 2 tsp Worcestershire sauce
- 1 tsp salt
- 1 tsp black pepper
- 1 tsp Tabasco or cayenne pepper (optional, for spiciness)
*** Method
- Combine the Rub ingredients and rub onto both sides of the ribs (most on meaty side). Set aside to marinate for 20 minutes (or overnight).
- Preheat oven to 160°C/320°F (all oven types).
- Place ribs on a tray in a single layer. Pour apple cider underneath the ribs, cover with foil then bake for 1 hour 30 minutes or until the meat is pretty tender (Note 5).
- Remove from oven, turn up to 180°C/350°F. Remove foil, drizzle with olive oil, then return ribs to oven for 15 minutes or until rub becomes nice and crusty.
- Line a new tray with foil then baking / parchment paper (you'll thank me later).
- Remove ribs from oven, transfer to lined tray. Pour any juices from tray over the ribs.
- Flip ribs so the bonier side is up. Slather with Barbecue Sauce, then bake 10 minutes.
- Remove from oven, then turn ribs over so the meaty side is up. Slather with Barbecue Sauce, bake 5 minutes. Repeat 2 or 3 more times until you've got a thick glaze on the ribs.
- Cut ribs into individual or multiple rib portions and serve with remaining Barbcue Sauce!
**** BARBECUE SAUCE
- Place all ingredients in a saucepan and simmer over medium heat, stirring occasionally, for 45 minutes or until thickened.
- Adjust to taste: sweetness with brown sugar / honey, salt and sour with vinegar. Use for glazing ribs and as a sauce for serving.
